### ISSUE TITLE
OpenCV 2.4.5, 2.4.6 released

### ISSUE THREAD

**Issue by oskargargas** [Fl0p/OpenCV-iOS#1]
Hi,
Please consider updating to newest stable OpenCV version. It has many bug fixes, better parallelization of algorithms and better camera preview handling on iOS platform, not to mention native conversion between UIImage and cv::Mat.

Full change log is available here http://code.opencv.org/projects/opencv/wiki/ChangeLog.
Compiled iOS frameworks are available here http://sourceforge.net/projects/opencvlibrary/files/opencv-ios/.

If I'll have time for update my apps during next few weeks I'll prepare a pull request but please consider doing it asap.

Cheers,
OG

**Comment by Fl0p** [comment]
Look like you only one user of this spec
Wanna to contribute ?

**Comment by Fl0p** [comment]
Here the latest one v 2.4.6
 https://github.com/Fl0p/OpenCV-iOS/blob/master/OpenCV.podspec

also here v 2.4.5
https://github.com/Fl0p/OpenCV-iOS/blob/2.4.5/OpenCV.podspec

Hope specs will be available in cocoapods master repo soon

**Comment by oskargargas** [comment]
They're already in CocoaPods master. Thanks! I'll make a good use of it!
