### ISSUE TITLE
OpenCV 2.4.9

### ISSUE THREAD

**Issue by allenhumphreys** [Fl0p/OpenCV-iOS#14]
It seems someone else has published the podspec for 2.4.9 and has drastically altered the way it works and where the files come from. This is causing issues with our project and I'm attempting to get to the bottom of it. Any help on the matter would be greatly appreciated.

**Comment by ExoticObjects** [comment]
Agreed...

Changing from this:

pod 'OpenCV', '~> 2.4.8'

to this

pod 'OpenCV', '2.4.8'

fixed if for me.

If that's confusing, you can read up on semantic versioning here:
http://guides.cocoapods.org/using/the-podfile.html or here:
http://semver.org/

**Comment by allenhumphreys** [comment]
That's not confusing, I should only have to specify a version if I have a true code dependency. The problem is, the person who claimed the ownership of the podspec for version 2.4.9 completely rewrote the spec and left out some very important information. Not to mention, 2.4.9 downloads the files from sourceforge.net which is considerably slower than GitHub. We should go back to the old way, as it was correct.

**Comment by ExoticObjects** [comment]
I agree. I tried to contact the guy who changed the podspec, but to no
avail. Just pointing to 2.4.8 was a sufficient fix for me.

Do you have commit privileges on this project?

On Sat, Oct 11, 2014 at 11:34 PM, Allen Humphreys notifications@github.com
wrote:

> That's not confusing, I should only have to specify a version if I have a
> true code dependency. The problem is, the person who claimed the ownership
> of the podspec for version 2.4.9 completely rewrote the spec and left out
> some very important information. Not to mention, 2.4.9 downloads the files
> from sourceforge.net which is considerably slower than GitHub. We should
> go back to the old way, as it was correct.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Fl0p/OpenCV-iOS/issues/14#issuecomment-58772421.

## 

Jim Kremens
Co-Founder, Exotic Objects
M:917-885-1734
O:212-918-2025

**Comment by allenhumphreys** [comment]
Yes, I do, but I really want to resolve this issue. I've already specified 2.4.8 in the meantime. If the guy doesn't get back to me in a few days, I will file with cocoapods to have myself added as an owner of the podspec and hopefully help the Fl0p git project take back control.
