### ISSUE TITLE
Duplicate symbol in build phase in 2.4.4 and 2.4.5

### ISSUE THREAD

**Issue by mave99a** [Fl0p/OpenCV-iOS#2]
Use Cocoapod to integrate OpenCV.
2.4.3.2 builds well, however 2.4.4, 2.4.5 will run into following dup symbol problem: 

duplicate symbol __ZThn4_NK2cv4SURF11computeImplERKNS_3MatERNSt3__16vectorINS_8KeyPointENS4_9allocatorIS6_EEEERS1_ in:
    /Users/mao/work/projects/cam/levitagram/iOS/Pods/OpenCV/opencv2.framework/opencv2(surf.o)
duplicate symbol __ZThn4_NK2cv4SURF14descriptorSizeEv in:
    /Users/mao/work/projects/cam/levitagram/iOS/Pods/OpenCV/opencv2.framework/opencv2(surf.o)
duplicate symbol __ZThn4_NK2cv4SURF14descriptorTypeEv in:
    /Users/mao/work/projects/cam/levitagram/iOS/Pods/OpenCV/opencv2.framework/opencv2(surf.o)
ld: 21 duplicate symbols for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Fl0p** [comment]
1)
Try to reinstall pods:
- remove Pods/ folder and  .xcworkspace and Podfile.lock
- remove librarry libPods.a and framework opencv.framework if exist 
- type 'pod install' again
- open workspace

2)
Try to download OpenCV framework from here:
http://sourceforge.net/projects/opencvlibrary/files/opencv-ios/
and try to add it into you project without Cocoapods

Let me know if anything change.

**Comment by mave99a** [comment]
I still have the same problem after following 1).

**Comment by Fl0p** [comment]
what about 2) ?

**Comment by mave99a** [comment]
I didn't try 2) yet. I am using 2.4.3.2 for now.

**Comment by Fl0p** [comment]
Not sure:
is this podspec problem or framework compilation problem or opencv problem

Looks like same issue
http://stackoverflow.com/questions/16482218/opencv2-framework-opencv2surf-o-duplicate-symbols-for-architecture-armv7

**Comment by Fl0p** [comment]
Got it
Make sure you're NOT using the `-all_load` linker flag, use the `-ObjC` linker flag instead.
